# Cloudflare Worker 配置文件

name = "h2r-kf-ng4g"
main = "index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
name = "wechat-customer-service"
# 微信企业号配置
WECHAT_CORP_ID="wx74c026e563a3b7ed"
WECHAT_KF_SECRET="aKBJBDh78pLakiJUbT1s0so0V-cgDKHqawwE6SnoVcA"
WECHAT_KF_TOKEN="nJG4gQ"
WECHAT_KF_ENCODING_AES_KEY="jmC5OFQ8agUd1xwV7zttaAD5WlOu5IVCAfHtRotqsdC"

# 加密服务配置（由于 CF Worker CRYPTO 兼容性问题，需要单独部署）
CRYPTO_SERVICE_URL=" https://wecom-crypto.deno.dev"

# OpenAI API 配置
OPENAI_API_KEY="sk-njdxmppfjsegvndrbbrwtszdvuuidvwukzotuyrnlwncfooh"
OPENAI_BASE_URL="https://api.siliconflow.cn"
OPENAI_MODEL="Qwen/Qwen3-32B"
OPENAI_TIMEOUT=30000
# OPENAI_ORGANIZATION=org-your-org-id
# OPENAI_PROJECT=proj-your-project-id

# 系统提示词配置
SYSTEM_PROMPT="your are helpful assistant, reply in chinese, and reply in plain text format, text length should be less than 10240 characters" 


# KV存储配置（用于持久化对话历史）
[[kv_namespaces]]
binding = "CONVERSATIONS"
id = "da08a2c24ffa45388645ccdaf47f23b1"
preview_id = ""

# KV存储配置（用于消息处理状态跟踪）
[[kv_namespaces]]
binding = "MESSAGE_TRACKER"
id = "6c86b8071f254c81b37d54ab6c7ec7c2"
preview_id = ""